version: '2'
services:
  api:
    image: ulang/dss:latest
#    depends_on:
#      - db
    ports:
      - 8080:80
    volumes:
      - ./dss-code:/dss-code
      - ./work:/work
      - /etc/localtime:/etc/localtime:ro
    tty: true
  db:
    image: mongo
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./work:/work
      - /etc/localtime:/etc/localtime:ro
